### ISSUE TITLE
December '23: epic-stack catchup

### ISSUE THREAD

**Issue by ricardocosta** [ricardocosta/bank-fe#133]
## Description

December '23: Catchup on epic-stack changes 

- [x] https://github.com/epicweb-dev/epic-stack/commit/95b7549421e45b4a978e1bc3c21a7cd934823e12
- [x] https://github.com/epicweb-dev/epic-stack/commit/4a003be87a6822ac508263bc6e2a82585c81a2c1
- [x] https://github.com/epicweb-dev/epic-stack/commit/d5d0764aa95845d11bc70cc9f56b5f1a6416037f
