### ISSUE TITLE
January '24: epic-stack catchup

### ISSUE THREAD

**Issue by ricardocosta** [ricardocosta/bank-fe#218]
## Description

January '24: Catchup on epic-stack changes 
- [x] https://github.com/epicweb-dev/epic-stack/commit/b0158f8435d30e5db0843b6ae5d05c6ff3a0bfee
- [x] https://github.com/epicweb-dev/epic-stack/commit/22c08d6c0913cc14e3834de9f236d1624c75fe91
- [x] https://github.com/epicweb-dev/epic-stack/commit/68ebb0499496bbb6e0b3e3e2825f6e7e586dd172
- [x] https://github.com/epicweb-dev/epic-stack/commit/635e419e49c40ac8556566b4f2ec22f07dffc3ee
- [x] https://github.com/epicweb-dev/epic-stack/commit/04aececc5d3137713f9f01d132f3a25a122aff78
- [x] https://github.com/epicweb-dev/epic-stack/commit/a6b46acda8179ee4b1d394597a97f22187af6081
- [x] https://github.com/epicweb-dev/epic-stack/commit/bb0dda361d82dc5a83909f098a81e4b01f9d7647
- [ ] https://github.com/epicweb-dev/epic-stack/commit/97d789f737380be318f57425be9040ce360b12ce
- [x] https://github.com/epicweb-dev/epic-stack/commit/c59b9792f9284e7dd2c4208441df63c73927b732
- [x] https://github.com/epicweb-dev/epic-stack/commit/6eb46d0eb963bbd782bb5394c4861e821b731977
- [x] https://github.com/epicweb-dev/epic-stack/commit/748f50f90c0fe7e0f04fcfeb04343da198a8b327
- [x] https://github.com/epicweb-dev/epic-stack/commit/c9a17b3b164ca9fb2e1467ae7eb9aec570c68044
- [x] https://github.com/epicweb-dev/epic-stack/commit/90f4208395ab77605082a578e0e7e2cb0c2b66bc
