### ISSUE TITLE
February '24: epic-stack catchup

### ISSUE THREAD

**Issue by ricardocosta** [ricardocosta/bank-fe#219]
## Description

February '24: Catchup on epic-stack changes 
- [x] https://github.com/epicweb-dev/epic-stack/commit/43d5c92483584e742a2e651501480af532cb55d9
- [x] https://github.com/epicweb-dev/epic-stack/commit/bf559f59608b9ad82479f4db6e1f0d7eafed987c
- [x] https://github.com/epicweb-dev/epic-stack/commit/73af6b84a2635c22630c4530a1c2d472d566d2b6
- [x] https://github.com/epicweb-dev/epic-stack/commit/42cbbb72b6028bfa30f39ffe8aa3fbbdf6c8c314
- [x] https://github.com/epicweb-dev/epic-stack/commit/c88d682eb3e53da75b30059b635e242de1beb867
- [x] https://github.com/epicweb-dev/epic-stack/commit/b06301317937624af0a3d32e9d82fcecf937bab3
