### ISSUE TITLE
March '24: epic-stack catchup

### ISSUE THREAD

**Issue by ricardocosta** [ricardocosta/bank-fe#220]
## Description

March '24: Catchup on epic-stack changes 
- [x] https://github.com/epicweb-dev/epic-stack/commit/b7190e1ea8f9a4b8393252f056fa247e3e36edc1
- [ ] https://github.com/epicweb-dev/epic-stack/commit/fe5d18af4501f00c0580e885a90ce12abf8e2fe7
- [x] https://github.com/epicweb-dev/epic-stack/commit/1b866a22682d9b6f051e12323b022adb981130f1
- [x] https://github.com/epicweb-dev/epic-stack/commit/f8224422e2d4bd95eab3303ec1199b41369b3832
- [x] https://github.com/epicweb-dev/epic-stack/commit/108988fd61b9754cf3dc4c488bfc2239c09b2576
- [ ] https://github.com/epicweb-dev/epic-stack/commit/54a0f6c441b7be600800cfc7a5fffc24392162d2
- [x] https://github.com/epicweb-dev/epic-stack/commit/bd6a00a3eff3e6824451015347c96781ce12816e
- [x] https://github.com/epicweb-dev/epic-stack/commit/c047d75db53dfca4d73f22b3de8bbb593ec01732
- [x] https://github.com/epicweb-dev/epic-stack/commit/a77cd9b88aa09f20bc582fd2badb1612cb8c0989
