### ISSUE TITLE
April '24: epic-stack catchup

### ISSUE THREAD

**Issue by ricardocosta** [ricardocosta/bank-fe#221]
## Description

April '24: Catchup on epic-stack changes 
- [ ] https://github.com/epicweb-dev/epic-stack/commit/b637a2b2974bc9faf6de948ce13c5534ea11435a
- [ ] https://github.com/epicweb-dev/epic-stack/commit/d663177944e97f2705ec69482d3cc3c56865b2c8
- [ ] https://github.com/epicweb-dev/epic-stack/commit/4c9b2b1263867ba7b6682ffae2d975757752c94e
